# Generated by Django 5.1.1 on 2024-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dog_Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_For', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
